### ISSUE TITLE
Can't render my-project.dev

### ISSUE THREAD

**Issue by s10wen** [kapow-wp/kapow-skeleton#45]
## Expected Behaviour

`http://my-project.dev` should resolve.
`http://my-project.dev` should resolve.

## Actual Behaviour

I get a warning regarding https / encryption.

## Your Specifications

Similar to @mkjonesuk with https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1034 I can hit http://vvv.test/ and https://local.wordpress.test/ but not https://build.wordpress-develop.test or https://my-project.dev (my test Kapow! install).

I'm on a Mac and copied `~/vagrant-local/vvv-config.yml` to `~/vagrant-local/vvv-custom.yml` and added my project:

```
sites:
  # The wordpress-default configuration provides a default installation of the
  # latest version of WordPress.
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
    hosts:
      - local.wordpress.test

  # The wordpress-develop configuration is useful for contributing to WordPress.
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
    hosts:
      - src.wordpress-develop.test
      - build.wordpress-develop.test

  # Added for kapow
  my-project:
    hosts:
      - my-project.dev
    nginx_upstream: php71
```

At `/private/etc/hosts` I've added `192.168.50.4 my-project.dev`.

At `~/vagrant-local/config/nginx-config/sites/default.conf` I've tried various things, such as creating a self signed cert, trying to disable ssl and then `vagrant provision`:

```
server {
    listen       80 default_server;
    listen       443 ssl;
    root         /srv/www/default;
    # ssl on;
    # ssl_certificate /srv/config/nginx-config/sites/ssl/vvv.test.cert;
    # ssl_certificate_key /srv/config/nginx-config/sites/ssl/vvv.test.key;
    server_name  vvv.dev vvv.test vvv.local vvv.localhost;
```

Would be good to figure out what I'm missing!

Cheers,
Simon.
